site_name: Fontsize's Page

theme:
  # name: readthedocs
  name: material

nav:
  - Index: index.md
  - About: about.md
  - Notes:
    - Algebra: 
      - Homepage: Notes/Algebra.md
      - Positive Definite: Notes/Algebra/1-positive-definite.md
      - Rank: Notes/Algebra/2-rank.md
    - Analysis: Notes/Analysis.md
    - NumericalAlgebra:
      - Homepage: Notes/NumericalAlgebra.md
      - ch1: Notes/NumericalAlgebra/ch1-线性方程组的直接解法(Ax=b).md
      - ch2: Notes/NumericalAlgebra/ch2-敏度分析与误差分析.md
      - ch3: Notes/NumericalAlgebra/ch3-LeastSquare.md
      - ch4: Notes/NumericalAlgebra/ch4-古典迭代法.md
      - ch5: Notes/NumericalAlgebra/ch5-梯度法.md
      - ch6: Notes/NumericalAlgebra/ch6-非对称特征值问题的计算方法.md
      - ch7: Notes/NumericalAlgebra/ch7-对称特征值问题的计算方法.md
    - 优化实用算法:
      - Homepage: Notes/优化实用算法.md
      - 单纯形法: Notes/优化实用算法/单纯形法.md


markdown_extensions:
  - pymdownx.arithmatex: # 数学公式内嵌mathjax
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists # 支持嵌套列表

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js