site_name: Fontsize's Page

theme:
  name: readthedocs

nav:
  - Index: index.md
  - About: about.md
  - Notes:
    - Algebra: Notes/Algebra.md
    - Analysis: Notes/Analysis.md
    - Numerical Methods: Notes/NumericalAlgebra.md

markdown_extensions:
  - pymdownx.arithmatex: # 数学公式内嵌mathjax
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists # 支持嵌套列表

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js