site_name: Fontsize's Page

theme:
  name: readthedocs

nav:
  - Index: index.md
  - About: about.md
  - Notes:
    - Algebra: Notes/Algebra.md
    - Analysis: Notes/Analysis.md
    - Numerical Algebra: Notes/NumericalAlgebra.md
  # - NumericalAlgebra:
  #   - Homepage: Notes/NumericalAlgebra.md
  #   - ch1: Notes/NumericalAlgebra/ch1.md
  #   - ch2: Notes/NumericalAlgebra/ch2.md
  #   - ch3: Notes/NumericalAlgebra/ch3.md
  #   - ch4: Notes/NumericalAlgebra/ch4.md
  #   - ch5: Notes/NumericalAlgebra/ch5.md
  #   - ch6: Notes/NumericalAlgebra/ch6.md
  #   - ch7: Notes/NumericalAlgebra/ch7.md


markdown_extensions:
  - pymdownx.arithmatex: # 数学公式内嵌mathjax
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists # 支持嵌套列表

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js