site_name: Fontsize's Page
site_url: https://321fontsize.github.io/Mkdocs/

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.action.edit
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
  font:
    code: Cascadia


nav:
  - Index: index.md
  - About: about.md
  - Math-Notes:
    - Math-Notes/index.md
    - 代数: 
      - Math-Notes/Algebra/index.md
      - 正定: Math-Notes/Algebra/1-positive-definite.md
      - 秩: Math-Notes/Algebra/2-rank.md
      - QR分解: Math-Notes/Algebra/3-QRDecomposition.md
      - Schur分解: Math-Notes/Algebra/4-SchurDecomposition.md
      - 矩阵范数: Math-Notes/Algebra/5-matrix-norm.md
      - 矩阵可逆与范数之间的关系-矩阵扰动: Math-Notes/Algebra/6-Perturbations.md
    - 分析: 
      - Math-Notes/Analysis/index.md
      - Dense Set: Math-Notes/Analysis/1-dense_set.md
    - 数值线性代数:
      - Math-Notes/NumericalAlgebra/index.md
      - 线性方程组的直接解法(Ax=b): Math-Notes/NumericalAlgebra/ch1-线性方程组的直接解法(Ax=b).md
      - 敏度分析与误差分析: Math-Notes/NumericalAlgebra/ch2-敏度分析与误差分析.md
      - 最小二乘: Math-Notes/NumericalAlgebra/ch3-LeastSquare.md
      - 古典迭代法: Math-Notes/NumericalAlgebra/ch4-古典迭代法.md
      - 梯度法: Math-Notes/NumericalAlgebra/ch5-梯度法.md
      - 非对称特征值问题: Math-Notes/NumericalAlgebra/ch6-非对称特征值问题的计算方法.md
      - 对称特征值问题: Math-Notes/NumericalAlgebra/ch7-对称特征值问题的计算方法.md
    - 优化实用算法:
      - Math-Notes/Optimize/index.md
      - 单纯形法: Math-Notes/Optimize/simplex_algorithm.md


markdown_extensions:
  - pymdownx.arithmatex: # 数学公式内嵌mathjax
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists # 支持嵌套列表

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js